# Conclusion
In this study, we examined the relationships between MVPA (moderate to vigorous physical activity time) and different variables, where we especially focused on AVG (active video games) related variables. From our graphs, we observed that MVPA doesn't have a clear relationship with times but do have some variations between different time points. Our main finding is that AVG associates with MVPA, meaning that playing active video games can help increase children to do more physical activities. The willing of children to play active video games can also lead them into doing more physical activities, which is likely due to them playing more AVGs. Our conclusions are partially based on questionnaires, which we tested to be mostly reliable in this study. Further studies can be done on verifying the findings through more technical methods.These insights support the broader motivation of our project, which is to explore whether active games can serve as a practical tool to help reduce sedentary habits and make physical activity more enjoyable for children.
