---
title: "Proposal"
format: html
---

# Introduction

The topic of this project focuses on how active video games — games that require players to move their body to play — can help to reduce sedentary habits among children. We choose this topic because we have personally experienced the effects of sitting for long hours in front of computer and phone. At the start of this October I suffered from neck and shoulder ache due to my poor posture and inactivity. Eventually, I bought a monitor stand and started doing light exercises to fix it.So we are interested in how similar inactivity affects kids who spend even more time on screens, and whether games that involve movement could make physical activity more enjoyable for them. This project aims to explore how playing active video games influences children's daily activity levels, motivation, and preferences for active versus sedentary play, and whether these games can serve as a creative bridge between digital entertainment and a healthier lifestyle.

# Data

The data set we use in this study is from "The influence of active video game play upon physical activity and screen-based activities in sedentary children" published by Department of Agriculture on DATA.GOV (https://catalog.data.gov/dataset/data-from-the-influence-of-active-video-game-play-upon-physical-activity-and-screen-based--33694). The data were collected from children who wer instructed to fill-out describing the previous day's activities at baseline, 2, 4, 6 and 10 weeks. This dataset also includes the demographic data (weight, height, gender, race, ethnicity, birth year) of the children and the liking data of the children for baseline, week 6 and week 10 where children rated how much they want to perform physical/sedentary activities on a scales of 1-10. Additional questionnaire data were collected to measure exercise self-efficacy using the Children’s Self-Perceptions of Adequacy in and Predilection for Physical Activity Scale (CSAPPA). Motivation for physical activity was evaluated using the Behavioral Regulations in Exercise Questionnaire, 2nd Edition (BREQ-2). Modified versions of the BREQ-2 were also used to assess motivation toward active video games—framing the questions around engagement in active gaming rather than general physical activity, and to evaluate motivation for sedentary video games, adapting the items to focus on sedentary gaming behaviors. In addition, physical activity related parenting practices were measured using the Activity Support Scale for Multiple Groups (ACTS-MG). The data is static with the last metadata update on June 5, 2025. A potential issue is that the data relies partly on self-reported activities, which might introduce response bias.
